### ISSUE TITLE
V2 TODO

### ISSUE THREAD

**Issue by jisungbin** [brave-people/Dev-Event-Android#12]
- [ ] 즐겨찾기 기능 롤백
- [ ] 오프라인 모드 롤백
- [ ] 이벤트 추가 요청
- [ ] 이벤트 추가 키워드 알림
- [ ] 디자인 개선 (Material You)
- [ ] 무시할 이벤트 태그 지정
- [ ] 카카오톡으로 이벤트 공유
- [ ] 백그라운드 상태에서 이벤트 자동 갱신
- [ ] 다크모드 지원
