### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jisungbin** [brave-people/Dev-Event-Android#27]
- [x] Memory Leak 해결 (Leak Canary 로 잡히는 게 있음)
- [ ] Firebase Analytics 및 자체 Logger 구성 (ref: [tivi/core](https://github.com/chrisbanes/tivi/tree/main/core))
- [ ] NavigationBar 색상 BottomNavigationView 와 통일
- [ ] Fragment 개선 (목표: 카톡처럼 완벽하게 만들기)
