### ISSUE TITLE
V1 TODO

### ISSUE THREAD

**Issue by jisungbin** [brave-people/Dev-Event-Android#4]
- [x] **클린 아키텍처 적용**
- [x] MVI 패턴으로 변경

---

- [ ] 에러 핸들 엑티비티 추가
- [ ] 이벤트 공유하기 (카카오링크) 추가
- [x] `LazyEvent` events change animation; https://stackoverflow.com/a/64922966/14299073
- [x] 이벤트 알림이 하루만 작동하는 버그 수정
- [x] 새로운 이벤트 알림 안뜸
- [x] 새로운 이벤트 키워드 알림 (설정 추가)
- [x] 새로운 이벤트 노티피케이션 알림 on/off (기본값: false)
- [x] 앱 설정 UI 제작
- [x] 크롤링 자동 새로고침 on/off (1일 주기)
- [x] 태그 지정 보기
- [x] 이벤트 검색 대소문자 무시 넣기
- [x] 크롬 사용 가능한지 체크 (Web.kt)
- [x] Convert `Box` to `ConstraintLayout`
- [x] Code clean-up (refactoring)
- [x] cancel task (AlarmUtil.kt)
- [x] SwipeDown to dismiss (`BottomSheet`)
- [x] Change `TagView` to Clickable `Chip`
- [x] fix inner shadow issue (Tag UI)
- [x] `SwipeRefresh`로 크롤링 새로고침 
- [x] `LazyEvent` sticky header - header date
- [x] clear `TextFieldValue` not working (at MainActivity.kt search toolbar)
- [x] 이벤트 자세히보기 `BottomSheet`
- [x] ~~이벤트 즐겨찾기 아이콘 채색 안되있는 버그 해결 (원인 파악 불가)~~
- [x] ~~이벤트 자세히보기 `Dialog`~~ (`BottomSheet`로 대체되어야 함)
- [x] ~~Kotlin `1.5.10` -> `1.5.20`~~ (compose 의존)
- [x] ~~`ErrorDialog` title centering~~ (remove `lottie`)
- [x] ~~`Searcher` item add/remove animation (remove `Searcher`)~~
- [x] ~~`searcherVisible` state - not working properly~~ (remove `Searcher`)
- [x] ~~Check notification channel already created~~ (필요 없는 작업: [[참고]](https://developer.android.com/training/notify-user/channels#CreateChannel))
- [x] ~~`LazyEvent` 중간 광고(`admob`) - 설정에서 toggle 가능 (기본값 off)~~ _[만 18세라 에드몹 불가능]_
- [x] ~~`Event` - date string, category string max length~~

**Comment by jisungbin** [comment]
CLOSE
